#!/bin/python3

import math
import os
import random
import re
import sys


#
# Complete the 'compareTriplets' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts following parameters:
#  1. INTEGER_ARRAY a
#  2. INTEGER_ARRAY b
#

def compareTriplets(a, b):
  Alice=0
  Bob=0
  for i in range(3):

    if a[i]>b[i]:
        Alice += 1
        
    elif b[i]>a[i]:
        Bob +=1
    else:
          continue
  return [Alice, Bob]
      
if __name__ == '__main__':
  
    a = list(map(int, input().strip().split()))

    b = list(map(int, input().strip().split()))
print(*compareTriplets(a, b))
